export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const GET_ROLE_REQUEST = 'GET_ROLE_REQUEST';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE';

export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';

export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST';
export const UPDATE_ROLENAME = 'UPDATE_ROLENAME';

export const GET_ROLE_ID_REQUEST = 'GET_ROLE_ID_REQUEST';
export const GET_ROLE_ID_SUCCESS = 'GET_ROLE_ID_SUCCESS';
